# Production environment specific settings
baseURL = "https://lasmontanasinn.com/"
publishDir = "public"

# Enable HTML minification
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = false
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = false
      keepDefaultAttrVals = false
      keepDocumentTags = true
      keepEndTags = false
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

# Improve rendering performance
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

# Set caching headers
[server]
  [[server.headers]]
    for = "/**/*.{css,js,jpg,jpeg,png,gif,ico,svg,webp,woff,woff2,ttf}"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
  [[server.headers]]
    for = "/**/*.html"
    [server.headers.values]
      Cache-Control = "public, max-age=0, must-revalidate" 